$out = 'C:\code2\script.js'
$lines = [System.Collections.Generic.List[string]]::new()

$lines.Add('/* BloodLink Pro — Core Logic v2 */')
$lines.Add('')
$lines.Add('const KEYS = { session:''blp_session'', emergencies:''blp_emergencies'' };')
$lines.Add('const store = {')
$lines.Add('  get:    k => { try { return JSON.parse(localStorage.getItem(k) || ''[]''); } catch { return []; } },')
$lines.Add('  set:    (k,v) => localStorage.setItem(k, JSON.stringify(v)),')
$lines.Add('  getObj: k => { try { return JSON.parse(localStorage.getItem(k) || ''null''); } catch { return null; } },')
$lines.Add('  setObj: (k,v) => localStorage.setItem(k, JSON.stringify(v)),')
$lines.Add('  remove: k => localStorage.removeItem(k)')
$lines.Add('};')
$lines.Add('')
$lines.Add('const JB_KEY    = ''$2a$10$gnr12wuvoYipciglW9hglOFE5FfQ9q0yU01ZBv8dwhwaNMfUSU.NW'';')
$lines.Add('const JB_USERS  = ''69bc2150aa77b81da9fcb1e3'';')
$lines.Add('const JB_DONORS = ''69bc22a2b7ec241ddc82de74'';')
$lines.Add('const JB_MARKET = ''69bc22a2b7ec241ddc82de79'';')
$lines.Add('const JB_BASE   = ''https://api.jsonbin.io/v3/b'';')
$lines.Add('')
$lines.Add('async function jbGet(binId) {')
$lines.Add('  try {')
$lines.Add('    const res = await fetch(JB_BASE + ''/'' + binId + ''/latest'', {')
$lines.Add('      method: ''GET'',')
$lines.Add('      headers: { ''X-Master-Key'': JB_KEY, ''X-Bin-Meta'': ''false'' }')
$lines.Add('    });')
$lines.Add('    if (!res.ok) { console.error(''jbGet error:'', res.status); return null; }')
$lines.Add('    const data = await res.json();')
$lines.Add('    return data.record || data || {};')
$lines.Add('  } catch(e) { console.error(''jbGet failed:'', e.message); return null; }')
$lines.Add('}')
$lines.Add('')
$lines.Add('async function jbSet(binId, data) {')
$lines.Add('  try {')
$lines.Add('    const res = await fetch(JB_BASE + ''/'' + binId, {')
$lines.Add('      method: ''PUT'',')
$lines.Add('      headers: { ''Content-Type'': ''application/json'', ''X-Master-Key'': JB_KEY },')
$lines.Add('      body: JSON.stringify(data)')
$lines.Add('    });')
$lines.Add('    if (!res.ok) { console.error(''jbSet error:'', res.status); return false; }')
$lines.Add('    return true;')
$lines.Add('  } catch(e) { console.error(''jbSet failed:'', e.message); return false; }')
$lines.Add('}')

[System.IO.File]::WriteAllLines($out, $lines, [System.Text.Encoding]::UTF8)
Write-Host "Part1 done: $((Get-Item $out).Length) bytes"
