$f = "C:\code2\script.js"
$e = [System.Text.Encoding]::UTF8
$w = [System.IO.File]

$w::WriteAllText($f, "", $e)

function A($t) { $w::AppendAllText($f, $t + "`n", $e) }

A "// BloodLink Pro - script.js (HackForce / Satish Kumar Nishad)"
A "const API_KEY = '`$2a`$10`$gnr12wuvoYipciglW9hglOFE5FfQ9q0yU01ZBv8dwhwaNMfUSU.NW';"
A "const BIN_USERS = '69bc2150aa77b81da9fcb1e3';"
A "const BIN_DONORS = '69bc22a2b7ec241ddc82de74';"
A "const BIN_MARKET = '69bc22a2b7ec241ddc82de79';"
A "const BASE_URL = 'https://api.jsonbin.io/v3/b';"
A ""
A "async function jbGet(binId) {"
A "  try {"
A "    const r = await fetch(BASE_URL + '/' + binId + '/latest', { headers: { 'X-Master-Key': API_KEY } });"
A "    if (!r.ok) return null;"
A "    const d = await r.json();"
A "    return d.record || null;"
A "  } catch(e) { return null; }"
A "}"
A ""
A "async function jbPut(binId, data) {"
A "  try {"
A "    const r = await fetch(BASE_URL + '/' + binId, {"
A "      method: 'PUT',"
A "      headers: { 'Content-Type': 'application/json', 'X-Master-Key': API_KEY },"
A "      body: JSON.stringify(data)"
A "    });"
A "    return r.ok;"
A "  } catch(e) { return false; }"
A "}"
A ""
A "async function getUsers() {"
A "  const cloud = await jbGet(BIN_USERS);"
A "  if (cloud && Array.isArray(cloud.users)) { localStorage.setItem('blp_uc', JSON.stringify(cloud.users)); return cloud.users; }"
A "  const c = localStorage.getItem('blp_uc'); return c ? JSON.parse(c) : [];"
A "}"
A "async function saveUsers(arr) { localStorage.setItem('blp_uc', JSON.stringify(arr)); return await jbPut(BIN_USERS, { users: arr }); }"
A ""
A "async function getDonors() {"
A "  const cloud = await jbGet(BIN_DONORS);"
A "  if (cloud && Array.isArray(cloud.donors)) { localStorage.setItem('blp_dc', JSON.stringify(cloud.donors)); return cloud.donors; }"
A "  const c = localStorage.getItem('blp_dc'); return c ? JSON.parse(c) : [];"
A "}"
A "async function saveDonors(arr) { localStorage.setItem('blp_dc', JSON.stringify(arr)); return await jbPut(BIN_DONORS, { donors: arr }); }"
A ""
A "async function getMarket() {"
A "  const cloud = await jbGet(BIN_MARKET);"
A "  if (cloud && Array.isArray(cloud.market)) { localStorage.setItem('blp_mc', JSON.stringify(cloud.market)); return cloud.market; }"
A "  const c = localStorage.getItem('blp_mc'); return c ? JSON.parse(c) : [];"
A "}"
A "async function saveMarket(arr) { localStorage.setItem('blp_mc', JSON.stringify(arr)); return await jbPut(BIN_MARKET, { market: arr }); }"
A ""
A "function currentUser() { const u = localStorage.getItem('blp_user'); return u ? JSON.parse(u) : null; }"
A "function setCurrentUser(u) { localStorage.setItem('blp_user', JSON.stringify(u)); }"
A "function logout() { localStorage.removeItem('blp_user'); window.location.href = 'login.html'; }"
A ""
A "function showToast(msg, type) {"
A "  let t = document.getElementById('blp-toast');"
A "  if (!t) { t = document.createElement('div'); t.id = 'blp-toast'; t.style.cssText = 'position:fixed;bottom:24px;left:50%;transform:translateX(-50%);padding:12px 24px;border-radius:8px;color:#fff;font-weight:600;z-index:9999;font-size:14px;transition:opacity .4s'; document.body.appendChild(t); }"
A "  t.textContent = msg;"
A "  t.style.background = type === 'success' ? '#27ae60' : type === 'error' ? '#e74c3c' : '#2980b9';"
A "  t.style.opacity = '1';"
A "  clearTimeout(t._timer);"
A "  t._timer = setTimeout(function(){ t.style.opacity = '0'; }, 3000);"
A "}"
A ""
A "function setupHamburger() {"
A "  const btn = document.getElementById('hamburger');"
A "  const menu = document.getElementById('nav-menu');"
A "  if (!btn || !menu) return;"
A "  btn.addEventListener('click', function(e){ e.stopPropagation(); menu.classList.toggle('open'); });"
A "  document.addEventListener('click', function(e){ if (!menu.contains(e.target) && e.target !== btn) menu.classList.remove('open'); });"
A "}"
A ""
A "function getDeviceFingerprint() {"
A "  const sig = [navigator.userAgent, navigator.language, screen.width+'x'+screen.height, screen.colorDepth, new Date().getTimezoneOffset(), navigator.hardwareConcurrency||0, navigator.platform||'', navigator.vendor||'', navigator.plugins ? navigator.plugins.length : 0].join('|');"
A "  let h = 0; for (let i = 0; i < sig.length; i++) { h = ((h << 5) - h) + sig.charCodeAt(i); h |= 0; }"
A "  return Math.abs(h).toString(36);"
A "}"
A ""
A "function trackVisitor() {"
A "  const fp = getDeviceFingerprint();"
A "  const seen = JSON.parse(localStorage.getItem('blp_seen_fps') || '[]');"
A "  let count = parseInt(localStorage.getItem('blp_vc') || '0');"
A "  if (!seen.includes(fp)) { seen.push(fp); count++; localStorage.setItem('blp_seen_fps', JSON.stringify(seen)); localStorage.setItem('blp_vc', count); }"
A "  const el = document.getElementById('visitor-count'); if (el) el.textContent = count;"
A "}"

A "async function initLogin() {"
A "  const form = document.getElementById('login-form');"
A "  if (!form) return;"
A "  form.addEventListener('submit', async function(e) {"
A "    e.preventDefault();"
A "    const email = form.querySelector('[name=email]').value.trim().toLowerCase();"
A "    const pass = form.querySelector('[name=password]').value;"
A "    const btn = form.querySelector('button[type=submit]');"
A "    btn.disabled = true; btn.textContent = 'Logging in...';"
A "    const users = await getUsers();"
A "    const user = users.find(u => u.email.toLowerCase() === email);"
A "    if (!user) { showToast('Email not found. Please register first.', 'error'); btn.disabled = false; btn.textContent = 'Login'; return; }"
A "    if (user.password !== pass) { showToast('Wrong password.', 'error'); btn.disabled = false; btn.textContent = 'Login'; return; }"
A "    setCurrentUser(user);"
A "    showToast('Login successful!', 'success');"
A "    setTimeout(function(){ window.location.href = 'dashboard.html'; }, 800);"
A "  });"
A "}"
A ""
A "async function initRegister() {"
A "  const form = document.getElementById('register-form');"
A "  if (!form) return;"
A "  form.addEventListener('submit', async function(e) {"
A "    e.preventDefault();"
A "    const name = form.querySelector('[name=name]').value.trim();"
A "    const email = form.querySelector('[name=email]').value.trim().toLowerCase();"
A "    const pass = form.querySelector('[name=password]').value;"
A "    const bloodEl = form.querySelector('[name=blood]');"
A "    const blood = bloodEl ? bloodEl.value : 'Unknown';"
A "    const btn = form.querySelector('button[type=submit]');"
A "    if (!name || !email || !pass) { showToast('Please fill all fields.', 'error'); return; }"
A "    btn.disabled = true; btn.textContent = 'Registering...';"
A "    const users = await getUsers();"
A "    if (users.find(u => u.email.toLowerCase() === email)) {"
A "      showToast('Email already registered. Please login.', 'error');"
A "      btn.disabled = false; btn.textContent = 'Register'; return;"
A "    }"
A "    const newUser = { id: Date.now(), name, email, password: pass, blood, joined: new Date().toISOString() };"
A "    users.push(newUser);"
A "    const ok = await saveUsers(users);"
A "    showToast(ok ? 'Registration successful! Please login.' : 'Registered (offline). Login on this device.', ok ? 'success' : 'info');"
A "    setTimeout(function(){ window.location.href = 'login.html'; }, 1200);"
A "  });"
A "}"
A ""
A "async function initDonor() {"
A "  const form = document.getElementById('donor-form');"
A "  if (!form) return;"
A "  form.addEventListener('submit', async function(e) {"
A "    e.preventDefault();"
A "    const btn = form.querySelector('button[type=submit]');"
A "    btn.disabled = true; btn.textContent = 'Submitting...';"
A "    const donor = {"
A "      id: Date.now(),"
A "      name: form.querySelector('[name=name]').value.trim(),"
A "      blood: form.querySelector('[name=blood]').value,"
A "      city: form.querySelector('[name=city]').value.trim(),"
A "      phone: form.querySelector('[name=phone]').value.trim(),"
A "      age: form.querySelector('[name=age]') ? form.querySelector('[name=age]').value : '',"
A "      date: new Date().toISOString()"
A "    };"
A "    if (!donor.name || !donor.blood || !donor.city || !donor.phone) {"
A "      showToast('Please fill all required fields.', 'error');"
A "      btn.disabled = false; btn.textContent = 'Register as Donor'; return;"
A "    }"
A "    const donors = await getDonors();"
A "    donors.push(donor);"
A "    const ok = await saveDonors(donors);"
A "    showToast(ok ? 'Donor registered successfully!' : 'Saved locally (cloud sync pending).', ok ? 'success' : 'info');"
A "    setTimeout(function(){ form.reset(); btn.disabled = false; btn.textContent = 'Register as Donor'; }, 1200);"
A "  });"
A "}"
A ""
A "async function initSearch() {"
A "  const form = document.getElementById('search-form');"
A "  const results = document.getElementById('search-results');"
A "  if (!form || !results) return;"
A "  form.addEventListener('submit', async function(e) {"
A "    e.preventDefault();"
A "    const blood = form.querySelector('[name=blood]').value;"
A "    const city = (form.querySelector('[name=city]').value || '').trim().toLowerCase();"
A "    results.innerHTML = '<p style=text-align:center>Searching...</p>';"
A "    const donors = await getDonors();"
A "    const found = donors.filter(d => (!blood || d.blood === blood) && (!city || d.city.toLowerCase().includes(city)));"
A "    if (!found.length) { results.innerHTML = '<p style=color:#e74c3c;text-align:center>No donors found.</p>'; return; }"
A "    results.innerHTML = found.map(d => '<div class=donor-card><div class=donor-blood>' + d.blood + '</div><div class=donor-info><h3>' + d.name + '</h3><p>City: ' + d.city + '</p><p>Phone: ' + d.phone + '</p></div></div>').join('');"
A "  });"
A "}"

A "async function initDashboard() {"
A "  const user = currentUser();"
A "  const nameEl = document.getElementById('user-name');"
A "  if (nameEl) nameEl.textContent = user ? user.name : 'Guest';"
A "  const logoutBtn = document.getElementById('logout-btn');"
A "  if (logoutBtn) logoutBtn.addEventListener('click', logout);"
A "  trackVisitor();"
A "  const [donors, market] = await Promise.all([getDonors(), getMarket()]);"
A "  const td = document.getElementById('total-donors'); if (td) td.textContent = donors.length;"
A "  const tt = document.getElementById('total-transactions'); if (tt) tt.textContent = market.length;"
A "  const tu = document.getElementById('total-units'); if (tu) tu.textContent = market.reduce((s,t) => s + (parseInt(t.qty)||1), 0);"
A "  renderCharts(donors, market);"
A "  renderRecentActivity(donors, market);"
A "}"
A ""
A "function renderCharts(donors, market) {"
A "  const barCtx = document.getElementById('bloodTypeChart');"
A "  if (barCtx) {"
A "    const types = ['A+','A-','B+','B-','AB+','AB-','O+','O-'];"
A "    const counts = types.map(t => donors.filter(d => d.blood === t).length);"
A "    const max = Math.max(...counts, 1);"
A "    const colors = counts.map(c => { const i = Math.round(80 + (c/max)*175); return 'rgb('+i+',30,30)'; });"
A "    if (window._barChart) window._barChart.destroy();"
A "    window._barChart = new Chart(barCtx, { type:'bar', data:{ labels:types, datasets:[{ label:'Donors', data:counts, backgroundColor:colors, borderRadius:6 }] }, options:{ responsive:true, animation:{ duration:1000, easing:'easeOutQuart' }, plugins:{ legend:{ display:false } }, scales:{ y:{ beginAtZero:true } } } });"
A "  }"
A "  const donutCtx = document.getElementById('marketChart');"
A "  if (donutCtx) {"
A "    const buys = market.filter(t => t.type==='buy').length;"
A "    const sells = market.filter(t => t.type==='sell').length;"
A "    const total = buys + sells || 1;"
A "    const pct = Math.round((buys/total)*100);"
A "    if (window._donutChart) window._donutChart.destroy();"
A "    window._donutChart = new Chart(donutCtx, { type:'doughnut', data:{ labels:['Buys','Sells'], datasets:[{ data:[buys,sells], backgroundColor:['#e74c3c','#27ae60'], borderWidth:0 }] }, options:{ responsive:true, cutout:'70%', animation:{ duration:1000, easing:'easeOutQuart' }, plugins:{ legend:{ position:'bottom' } } }, plugins:[{ id:'centerText', afterDraw(chart){ const {ctx,chartArea:{left,right,top,bottom}}=chart; const cx=(left+right)/2,cy=(top+bottom)/2; ctx.save(); ctx.font='bold 22px Arial'; ctx.fillStyle='#e74c3c'; ctx.textAlign='center'; ctx.textBaseline='middle'; ctx.fillText(pct+'%',cx,cy); ctx.restore(); } }] });"
A "  }"
A "}"
A ""
A "function renderRecentActivity(donors, market) {"
A "  const el = document.getElementById('recent-activity');"
A "  if (!el) return;"
A "  const acts = [];"
A "  donors.slice(-5).forEach(d => acts.push({ time: new Date(d.date||Date.now()), html: '<div class=activity-item><span class=badge>DONOR</span> <b>'+d.name+'</b> ('+d.blood+') from '+d.city+'</div>' }));"
A "  market.slice(-5).forEach(t => acts.push({ time: new Date(t.date||Date.now()), html: '<div class=activity-item><span class=badge>'+t.type.toUpperCase()+'</span> '+(t.qty||1)+' unit(s) of <b>'+t.blood+'</b> - Rs.'+t.price+'</div>' }));"
A "  acts.sort((a,b) => b.time - a.time);"
A "  el.innerHTML = acts.length ? acts.slice(0,8).map(a=>a.html).join('') : '<p style=text-align:center;color:#999>No recent activity yet.</p>';"
A "}"
A ""
A "function renderBloodCards() {"
A "  const container = document.getElementById('blood-cards');"
A "  if (!container) return;"
A "  const types = [{t:'A+',p:1200},{t:'A-',p:1400},{t:'B+',p:1100},{t:'B-',p:1500},{t:'AB+',p:1300},{t:'AB-',p:1800},{t:'O+',p:1000},{t:'O-',p:2000}];"
A "  container.innerHTML = types.map(b => '<div class=blood-card><div class=blood-type-badge>'+b.t+'</div><div class=blood-price>Rs.'+b.p+'/unit</div><button class=btn-buy onclick=openBuyModal('+JSON.stringify(b.t)+','+b.p+')>Buy Now</button></div>').join('');"
A "}"
A ""
A "async function openBuyModal(blood, price) {"
A "  const user = currentUser();"
A "  if (!user) { showToast('Please login to buy.', 'error'); return; }"
A "  const qty = parseInt(prompt('How many units of ' + blood + '?', '1')) || 1;"
A "  const total = price * qty;"
A "  const commission = +(total * 0.05).toFixed(2);"
A "  const payable = +(total + commission).toFixed(2);"
A "  if (!confirm(qty + ' unit(s) of ' + blood + '\nBase: Rs.' + total + '\n5% fee: Rs.' + commission + '\nTotal: Rs.' + payable + '\n\nConfirm?')) return;"
A "  const market = await getMarket();"
A "  market.push({ id: Date.now(), type: 'buy', blood, qty, price, commission, total: payable, buyer: user.name, date: new Date().toISOString() });"
A "  await saveMarket(market);"
A "  showToast('Purchase recorded! Total: Rs.' + payable, 'success');"
A "  await loadMarketListings();"
A "}"
A ""
A "async function loadMarketListings() {"
A "  const market = await getMarket();"
A "  const histEl = document.getElementById('transaction-history');"
A "  if (histEl) {"
A "    histEl.innerHTML = market.length ? market.slice().reverse().map(t => '<div class=tx-item><span class=tx-badge>'+t.type.toUpperCase()+'</span> <b>'+t.blood+'</b> x'+(t.qty||1)+' @ Rs.'+t.price+' | '+(t.type==='sell'?'Net: Rs.'+t.net:'Total: Rs.'+t.total)+' | '+(t.buyer||t.seller||'')+' | '+new Date(t.date).toLocaleDateString()+'</div>').join('') : '<p style=text-align:center;color:#999>No transactions yet.</p>';"
A "  }"
A "  const listEl = document.getElementById('seller-listings');"
A "  if (listEl) {"
A "    const sells = market.filter(t => t.type==='sell');"
A "    listEl.innerHTML = sells.length ? sells.slice().reverse().map(t => '<div class=listing-item><span class=blood-badge>'+t.blood+'</span> '+(t.qty||1)+' unit(s) @ Rs.'+t.price+' | Seller: '+t.seller+' <button class=btn-small onclick=openBuyModal('+JSON.stringify(t.blood)+','+t.price+')>Buy</button></div>').join('') : '<p style=text-align:center;color:#999>No listings yet.</p>';"
A "  }"
A "}"
A ""
A "async function initPricing() {"
A "  renderBloodCards();"
A "  await loadMarketListings();"
A "  const clearBtn = document.getElementById('clear-history');"
A "  if (clearBtn) clearBtn.addEventListener('click', async function(){ if (!confirm('Clear all transaction history?')) return; await saveMarket([]); await loadMarketListings(); showToast('History cleared.', 'info'); });"
A "  const sellForm = document.getElementById('sell-form');"
A "  if (sellForm) {"
A "    sellForm.addEventListener('submit', async function(e) {"
A "      e.preventDefault();"
A "      const user = currentUser();"
A "      if (!user) { showToast('Please login to sell.', 'error'); return; }"
A "      const blood = sellForm.querySelector('[name=blood]').value;"
A "      const qty = parseInt(sellForm.querySelector('[name=qty]').value) || 1;"
A "      const price = parseFloat(sellForm.querySelector('[name=price]').value);"
A "      if (!blood || !price || price <= 0) { showToast('Fill all fields.', 'error'); return; }"
A "      const commission = +(price * qty * 0.05).toFixed(2);"
A "      const net = +(price * qty - commission).toFixed(2);"
A "      const market = await getMarket();"
A "      market.push({ id: Date.now(), type: 'sell', blood, qty, price, commission, net, seller: user.name, date: new Date().toISOString() });"
A "      await saveMarket(market);"
A "      showToast('Listed! Net after 5% commission: Rs.' + net, 'success');"
A "      sellForm.reset();"
A "      await loadMarketListings();"
A "    });"
A "  }"
A "}"
A ""
A "function playEmergencyHorn() {"
A "  const ctx = new (window.AudioContext || window.webkitAudioContext)();"
A "  let time = ctx.currentTime;"
A "  for (let i = 0; i < 4; i++) {"
A "    const o1 = ctx.createOscillator(), g1 = ctx.createGain();"
A "    o1.connect(g1); g1.connect(ctx.destination);"
A "    o1.frequency.setValueAtTime(960, time); g1.gain.setValueAtTime(0.6, time); g1.gain.exponentialRampToValueAtTime(0.001, time+0.6);"
A "    o1.start(time); o1.stop(time+0.6);"
A "    const o2 = ctx.createOscillator(), g2 = ctx.createGain();"
A "    o2.connect(g2); g2.connect(ctx.destination);"
A "    o2.frequency.setValueAtTime(760, time+0.6); g2.gain.setValueAtTime(0.6, time+0.6); g2.gain.exponentialRampToValueAtTime(0.001, time+1.2);"
A "    o2.start(time+0.6); o2.stop(time+1.2);"
A "    time += 1.2;"
A "  }"
A "}"
A ""
A "document.addEventListener('DOMContentLoaded', function() {"
A "  setupHamburger();"
A "  const page = location.pathname.split('/').pop() || 'index.html';"
A "  if (page === 'login.html') initLogin();"
A "  if (page === 'register.html') initRegister();"
A "  if (page === 'donor.html') initDonor();"
A "  if (page === 'search.html') initSearch();"
A "  if (page === 'dashboard.html') initDashboard();"
A "  if (page === 'pricing.html') initPricing();"
A "  if (page === 'index.html' || page === '') {"
A "    trackVisitor();"
A "    const sosBtn = document.getElementById('sos-btn') || document.getElementById('emergency-btn');"
A "    if (sosBtn) sosBtn.addEventListener('click', playEmergencyHorn);"
A "    const overlay = document.getElementById('welcome-overlay');"
A "    if (overlay) setTimeout(function(){ overlay.style.opacity='0'; overlay.style.pointerEvents='none'; }, 3000);"
A "  }"
A "});"
A ""
A "Write-Host 'script.js written successfully. Size: ' + ([System.IO.File]::ReadAllText($f).Length) + ' bytes'"
